# Generated by Django 5.2.7 on 2025-10-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_type', models.CharField(choices=[('FIRE', 'Fire Emergency'), ('MEDICAL', 'Medical Emergency'), ('ACCIDENT', 'Road Accident'), ('CRIME', 'Crime/Violence'), ('NATURAL', 'Natural Disaster'), ('OTHER', 'Other Emergency')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('voice_transcript', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='incident_images/')),
                ('ai_detection_result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_classification', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['-reported_at'], name='incidents_i_reporte_b3cd8c_idx'), models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'), models.Index(fields=['emergency_type'], name='incidents_i_emergen_741c41_idx')],
            },
        ),
    ]
